### ISSUE TITLE
How to get 'table name'?

### ISSUE THREAD

**Issue by feloxx** [blastrain/vitess-sqlparser#11]
use demo 

> stmt, err := sqlparser.Parse
> fmt.Printf("stmt = %+v\n", stmt)
> The output "stmt = &{Cache: Comments:[] Distinct: Hints: SelectExprs:[0xc420088e10] From:[0xc420089110 0xc420089140] Where:0xc42000a5c0 GroupBy:[] Having:<nil> OrderBy:[] Limit:<nil> Lock:}"

How do I get the value in the From
please help me

**Comment by goccy** [comment]
@feloxx 
You can get by the following code
```go
fmt.Println(stmt.(*sqlparser.Select).From[0].(*sqlparser.AliasedTableExpr).Expr.(sqlparser.TableName).Name.String())
```

**Comment by feloxx** [comment]
@goccy thank you
